PolitiekeBarometer_MVC/Controllers/AlertController.cs
using BL.Interfaces;
using BL.Managers;
using Domain;
using Domain.Dashboards;
using Domain.Platformen;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace PolitiekeBarometer_MVC.Controllers
{
    public class AlertController : BaseController
    {
        #region Alert
        public ActionResult LijstAlerts()
        {
            //Ophalen van alle alerts van een gebruiker
            IDashboardManager dashboardManager = new DashboardManager();
            string username = System.Web.HttpContext.Current.User.Identity.GetUserName();
            Dashboard dashboard = dashboardManager.getDashboard(username, Deelplatform.Naam);
            return View(dashboardManager.getAllDashboardAlerts(dashboard));
        }

        public ActionResult CreateAlert()
        {
            //Tonen van de UI voor createAlert, en elementen voor de zoekbalken
            IElementManager elementManager = new ElementManager();
            ViewBag.Suggestions = elementManager.getAllElementen(Deelplatform);
            Alert alert = new Alert();
            return View(alert);
        }
        [HttpPost]
        public ActionResult CreateAlert(FormCollection form, Alert alert)
        {
            //Form parsen naar een alert
            UnitOfWorkManager unitOfWorkManager = new UnitOfWorkManager();
            IDashboardManager dashboardManager = new DashboardManager(unitOfWorkManager);
            unitOfWorkManager.Save();
            alert = ParseFormToAlert(form, unitOfWorkManager);
            //Alert opslaan
            dashboardManager.createAlert(alert);

            //Terug naar lijst gaan
            return RedirectToAction("LijstAlerts");
        }
        private Alert ParseFormToAlert(FormCollection form, UnitOfWorkManager unitOfWorkManager)
        {
            IElementManager elementManager = new ElementManager(unitOfWorkManager);
            IDashboardManager dashboardManager = new DashboardManager(unitOfWorkManager);
            string username = System.Web.HttpContext.Current.User.Identity.GetUserName();
            Dashboard dashboard = dashboardManager.getDashboard(username, Deelplatform.Naam);

            //Element & vergelijkingselement ophalen
            Element element = elementManager.getElementByNaam(form["element"], Deelplatform);

            Element vergelijkingselement = elementManager.getElementByNaam(form["vergelijking"], Deelplatform);

            //OverschrijdingsWaarde Parsen
            int waarde = 0;
            int.TryParse(form["waarde"], out waarde);

            //DefaultWaarde voor Datatype en Datatype Parsen
            DataType bewerking = DataType.TOTAAL;
            var formbewerking = form["bewerking"].ToLower();
            switch (formbewerking)
            {
                case "totaal":
                    bewerking = DataType.TOTAAL;
                    break;
                case "percentage":
                    bewerking = DataType.PERCENTAGE;
                    break;
                default:
                    break;
            }

            //Operator Parsen
            var operatorS = "";
            var formOperator = form["operator"].ToLower();
            switch (formOperator)
            {
                case "stijging":
                    operatorS = ">";
                    break;
                case "daling":
                    operatorS = "<";
                    break;
                default:
                    break;
            }

            //Meldingen Parsen
            bool emailMelding = parseCheckbox(form["emailMelding"]);
            bool browserMelding = parseCheckbox(form["browserMelding"]);
            bool applicatieMelding = parseCheckbox(form["applicatieMelding"]);

            //Filters Parsen
            List<Domain.Dashboards.Filter> filters = new List<Domain.Dashboards.Filter>();
            Domain.Dashboards.Filter filter = parseFilter(form["Age"], FilterType.AGE);
            if (filter != null)
            {
                filters.Add(filter);
            }
            filter = parseFilter(form["Sentiment"], FilterType.SENTIMENT);
            if (filter != null)
            {
                filters.Add(filter);
            }
            filter = parseFilter(form["Retweet"], FilterType.RETWEET);
            if (filter != null)
            {
                filters.Add(filter);
            }
            filter = parseFilter(form["Geslacht"], FilterType.GESLACHT);
            if (filter != null)
            {
                filters.Add(filter);
            }
            filter = parseFilter(form["Opleiding"], FilterType.OPLEIDING);
            if (filter != null)
            {
                filters.Add(filter);
            }
            filter = parseFilter(form["Personaliteit"], FilterType.PERSONALITEIT);
            if (filter != null)
            {
                filters.Add(filter);
            }

            //Dataconfig 
            DataConfig dataConfig = new DataConfig()
            {
                Element = element,
                Vergelijking = vergelijkingselement,
                Filters = filters
            };

            //Alert configureren
            Alert alert = new Alert()
            {
                DataConfig = dataConfig,
                DataType = bewerking,
                Operator = operatorS,
                ApplicatieMelding = applicatieMelding,
                BrowserMelding = browserMelding,
                EmailMelding = emailMelding,
                Dashboard = dashboard,
                Meldingen = new List<Melding>(),
                Waarde = waarde,
                Status = AlertStatus.ACTIEF
            };
            return alert;
        }

        private Domain.Dashboards.Filter parseFilter(string filterS, FilterType type)
        {
            Domain.Dashboards.Filter filter = null;
            if (filterS != "geen")
            {
                bool isPositive;
                if (filterS == "Positief")
                {
                    isPositive = true;
                }
                else if (filterS == "Negatief")
                {
                    isPositive = false;
                }
                else
                {
                    return null;
                }
                filter = new Domain.Dashboards.Filter()
                {
                    Type = type,
                    IsPositive = isPositive
                };
            }
            return filter;
        }
        private bool parseCheckbox(string checkbox)
        {
            if (checkbox == "true")
            {
                return true;
            }
            return false;
        }

        public ActionResult EditAlert(int id)
        {
            IDashboardManager dashboardManager = new DashboardManager();
            IElementManager elementManager = new ElementManager();
            ViewBag.Suggestions = elementManager.getAllElementen(Deelplatform);
            Alert alert = dashboardManager.getAlert(id);
            ViewBag.Age = "Geen";
            ViewBag.Sentiment = "Geen";
            ViewBag.Retweet = "Geen";
            ViewBag.Geslacht = "Geen";
            ViewBag.Opleiding = "Geen";
            if (alert.DataConfig.Filters != null)
            {
                foreach (var item in alert.DataConfig.Filters)
                {
                    bool isPositive = item.IsPositive;
                    switch (item.Type)
                    {
                        case FilterType.AGE:
                            if (item.IsPositive)
                            {
                                ViewBag.Age = "Positief";
                            }
                            else
                            {
                                ViewBag.Age = "Negatief";
                            }
                            break;
                        case FilterType.GESLACHT:
                            if (item.IsPositive)
                            {
                                ViewBag.Geslacht = "Positief";
                            }
                            else
                            {
                                ViewBag.Geslacht = "Negatief";
                            }
                            break;
                        case FilterType.SENTIMENT:
                            if (item.IsPositive)
                            {
                                ViewBag.Sentiment = "Positief";
                            }
                            else
                            {
                                ViewBag.Sentiment = "Negatief";
                            }
                            break;
                        case FilterType.RETWEET:
                            if (item.IsPositive)
                            {
                                ViewBag.Retweet = "Positief";
                            }
                            else
                            {
                                ViewBag.Retweet = "Negatief";
                            }
                            break;
                        case FilterType.PERSONALITEIT:
                            if (item.IsPositive)
                            {
                                ViewBag.Personaliteit = "Positief";
                            }
                            else
                            {
                                ViewBag.Personaliteit = "Negatief";
                            }
                            break;
                        case FilterType.OPLEIDING:
                            if (item.IsPositive)
                            {
                                ViewBag.Age = "Positief";
                            }
                            else
                            {
                                ViewBag.Age = "Negatief";
                            }
                            break;

PolitiekeBarometer_MVC/Views/Alert/AlertDetail.cshtml
@{
    ViewBag.Title = "AlertDetail";
}

<h2>AlertDetail</h2>

PolitiekeBarometer_MVC/Views/Alert/Alerts.cshtml
@model IEnumerable<Domain.Alert>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.AlertId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ApplicatieMelding)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BrowserMelding)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.EmailMelding)
        </th>
        <th></th>
    </tr>
    @foreach (var item in Model)
    {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.AlertId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ApplicatieMelding)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.BrowserMelding)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.EmailMelding)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.AlertId }) |
            @Html.ActionLink("Details", "Details", new { id = item.AlertId }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.AlertId })
        </td>
    </tr>
    }
</table>

PolitiekeBarometer_MVC/Views/Alert/CreateAlert.cshtml
@model Domain.Alert
@{
    ViewBag.Title = "CreateAlert";
}
<style>
    .chosen-container {
        width: 100% !important;
    }

    .createAlert {
        border-radius: 5px;
        padding: 2rem;
        border: .5rem;
        border-color: darkgray;
        background-color: white;
    }

    .panel-collapse:after {
        content: "\2796";
    }

    .collapsed:after {
        content: '\02795';
        font-size: 13px;
        color: #777;
        margin-left: 5px;
    }
</style>
<div class="container">
    <div class="card ">
        <div class="card-header">Maak Nieuw Alert</div>
        <div class="card-body bg-dark">
            @using (Html.BeginForm("CreateAlert", "Alert"))
            {
                <div class="form-horizontal">
                    <div class="form-group createAlert" id="elementen">
                        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                        <h4 for="DataType">
                            Kies uw persoon, organisatie of thema
                            <i class="fa fa-arrow-down tooltipContainer">
                                <span class="tooltiptext">
                                    De waarde van de alert wordt bepaalt door het geselecteerde element<br /><br />
                                    Met een vergelijking wordt de waarde als volgt bepaald<br /><br />
                                    De waarde is &lt; 0 wanneer het vergelijkingselement groter is<br /><br />
                                    De waarde is &gt; 0 wanneer het geselecteerde element groter is
                                </span>
                            </i>
                        </h4>
                        <select id="test" class="chosen-select" name="element" style="width:100%;">
                            @foreach (var item in ViewBag.Suggestions)
                            {
                                <option value="@item.Naam">@item.Naam</option>
                            }
                        </select>

                        <a class="card-link panel-collapse collapsed" data-toggle="collapse" href="#collapseVergelijking" data-parent="#exampleAccordion">
                            <span class="nav-link-text">Vergelijking toevoegen</span>
                        </a>
                        <div class="collapse" id="collapseVergelijking">
                            <select id="test" class="chosen-select" name="vergelijking" style="width:100%;">
                                <option value="geen"></option>
                                @foreach (var item in ViewBag.Suggestions)
                                {
                                    <option value="@item.Naam">@item.Naam</option>
                                }
                            </select>
                        </div>
                    </div>
                    <div class="form-group createAlert">
                        <h3>
                            Waarde van de alert <br />
                        </h3>
                        <div id="waarde">
                            <label>
                                Waarde
                                <i class="fa fa-arrow-down tooltipContainer">
                                    <span class="tooltiptext">
                                        De waarde die overschreden moet worden:<br />
                                        Dit is een stijging/daling per dag
                                    </span>
                                </i>:
                            </label>
                            <input name="waarde" class="form-control w-25" type="number" />
                        </div>
                        <div id="bewerking">
                            <label>
                                Bewerking
                                <i class="fa fa-arrow-down tooltipContainer">
                                    <span class="tooltiptext">
                                        Bepaalt welk type data gebruikt bij het berekenen:<br />
                                        Totaal: totaal aantal posts<br />
                                        Percentage: relatieve stijging/trend
                                    </span>
                                </i>:
                            </label>
                            <div></div>
                            <select name="bewerking" class="form-control  w-25">
                                @foreach (Domain.DataType value in Enum.GetValues(typeof(Domain.DataType)))
                                {
                                    <option selected value="@value">
                                        @Enum.GetName(typeof(Domain.DataType), value).ToLower()
                                    </option>

                                }
                            </select>
                        </div>
                        <div id="operator">
                            <label>
                                Operator
                                <i class="fa fa-arrow-down tooltipContainer">
                                    <span class="tooltiptext">
                                        Bepaalt wanneer de alert wordt verzonden:<br />
                                        Stijging: Wanneer de huidige waarde groter is dan de ingestelde waarde<br />
                                        Daling: Wanneer de huidige waarde kleiner is dan de ingestelde waarde
                                    </span>
                                </i>:
                            </label>
                            <select name="operator" class="form-control w-25">
                                <option value="stijging">Stijging</option>
                                <option value="daling">Daling</option>
                            </select>
                        </div>

                    </div>

                    <div class="form-group createAlert">
                        <h4>Selecteer ontvangstmethode</h4>
                        <div class="form-group form-inline ">
                            @Html.LabelFor(model => model.EmailMelding, htmlAttributes: new { @class = "control-label col-md-2" })
                          
                          <input type="checkbox" value="true" name="emailMelding" />
                        </div>
                        <div class="form-group  form-inline">
                            @Html.LabelFor(model => model.BrowserMelding, htmlAttributes: new { @class = "control-label col-md-2" })
                            <input type="checkbox" value="true" name="browserMelding" />
                        </div>

                        <div class="form-group  form-inline">
                            @Html.LabelFor(model => model.ApplicatieMelding, htmlAttributes: new { @class = "control-label col-md-2" })
                            <input type="checkbox" value="true" name="applicatieMelding" />
                        </div>
                    </div>

                    <div class="form-group createAlert ">
                        <h4>Filters</h4>
                        @Html.Label("Age")
                        <div class="form-group">
                            <select class="chosen-select w-50" name="Age">
                                <option selected value="Geen"> Geen filter </option>
                                <option value="Positief"> +25j</option>
                                <option value="Negatief"> -25j</option>
                            </select>
                        </div>
                        @Html.Label("Sentiment")
                        <div class="form-group">
                            <select class="chosen-select w-50" name="Sentiment">
                                <option selected value="Geen"> Geen filter </option>
                                <option value="Positief"> Positief</option>
                                <option value="Negatief"> Negatief</option>
                            </select>
                        </div>
                        @Html.Label("Retweet")
                        <div class="form-group">
                            <select class="chosen-select w-50" name="Retweet">
                                <option selected value="Geen"> Geen filter </option>
                                <option value="Positief"> Enkel Retweets</option>
                                <option value="Negatief"> Geen Retweets</option>
                            </select>
                        </div>
                        @Html.Label("Geslacht")
                        <div class="form-group">
                            <select class="chosen-select w-50" name="Geslacht">
                                <option selected value="Geen"> Geen filter </option>
                                <option value="Positief"> Vrouw</option>
                                <option value="Negatief"> Man</option>
                            </select>
                        </div>
                        @Html.Label("Opleiding")
                        <div class="form-group">
                            <select class="chosen-select w-50" name="Opleiding">
                                <option selected value="Geen"> Geen filter </option>
                                <option value="Positief"> Hoge opleiding</option>
                                <option value="Negatief"> Lage opleiding</option>
                            </select>
                        </div>
                        @Html.Label("Personaliteit")
                        <div class="form-group">
                            <select class="chosen-select w-50" name="Personaliteit">
                                <option selected value="Geen"> Geen filter </option>
                                <option value="Positief"> Introvert</option>
                                <option value="Negatief"> Extravert</option>
                            </select>
                        </div>
                    </div>
                    <button type="submit" value="Submit" class="btn btn-primary">Save</button>

                </div>
            }
        </div>
    </div>
</div>

@section scripts {
    <script type="text/javascript">
    $(".chosen-select").chosen(
            {
                width: "100px",
                allow_single_deselect: true,
                disable_search_treshold: 10,
                no_results_text: "Geen elementen met deze naam gevonden"
            }
        );


    </script>
}

PolitiekeBarometer_MVC/Views/Alert/DetailsAlert.cshtml
@model Domain.Alert

@{
    ViewBag.Title = "DetailsAlert";
}

<h2>DetailsAlert</h2>

<div>
    <h4>Alert</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Interval)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Interval)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Waarde)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Waarde)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Operator)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Operator)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ApplicatieMelding)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ApplicatieMelding)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.BrowserMelding)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.BrowserMelding)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.EmailMelding)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.EmailMelding)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "EditAlert", new { id = Model.AlertId }) |
    @Html.ActionLink("Back to List", "LijstAlerts")
</p>

PolitiekeBarometer_MVC/Views/Alert/Index.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

PolitiekeBarometer_MVC/Views/Alert/LijstAlerts.cshtml
@model IEnumerable<Domain.Alert>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<div style="margin:20px">
    <h2>Lijst Alerts</h2>
    <p>
        @Html.ActionLink("Create New", "CreateAlert")
    </p>
</div>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ApplicatieMelding)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.BrowserMelding)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EmailMelding)
            </th>
            <th>
                Data instelling
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ApplicatieMelding)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.BrowserMelding)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EmailMelding)
                </td>
                <td>
                    Wanneer:
                    @if (item.DataType == Domain.DataType.TOTAAL)
                    {
                        <p>aantal posts</p>
                    }
                    @if (item.DataType == Domain.DataType.PERCENTAGE)
                    {
                        <span>De trend</span>
                    }
                    @Html.DisplayFor(modelItem => item.Operator)

                    @Html.DisplayFor(modelItem => item.Waarde)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Status)
                </td>
                <td>
                    @Html.ActionLink("Edit", "EditAlert", new { id = item.AlertId }) |
                    @Html.ActionLink("Details", "DetailsAlert", new { id = item.AlertId }) |
                    @Html.ActionLink("Delete", "DeleteAlert", new { id = item.AlertId })
                </td>
            </tr>
        }
    </table>

PolitiekeBarometer_MVC/Views/Alert/LijstMeldingen.cshtml
@model IEnumerable<Domain.Dashboards.Melding>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.IsPositive)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Titel)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Message)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MeldingDateTime)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.IsActive)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.IsPositive)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Titel)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Message)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MeldingDateTime)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.IsActive)
        </td>
        <td>
            @Html.ActionLink("Details", "Melding", new { id=item.MeldingId }) |
        </td>
    </tr>
}

</table>

PolitiekeBarometer_MVC/Views/Alert/MeldingDetail.cshtml
@model Domain.Dashboards.Melding

<div>
    <h4>Melding</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.IsPositive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsPositive)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Titel)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titel)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Message)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Message)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MeldingDateTime)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MeldingDateTime)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Lijst alle meldingen", "LijstMeldingen", "Alert")
</p>